### ISSUE TITLE
Message communication between one widget to selected widget of same class.

### ISSUE THREAD

**Issue by VirendraWankhede** [sjmf/ng2-mqtt-demo#6]
In my project there is more than one widget of same component class, and i want to pass the message from one component to selected widget of same component. But the message is showing to all widget of same component.

example : 
query widget is component of QueryComponent { } class and ClockComponent { } having three different widget of its. Now i want to send message from query component to one of the clock widget.
Actual result : It showing on all three widget of ClockComponent class.

Can you tell me is it possible to control on message sending ? 

Thanking You !

**Comment by sjmf** [comment]
It's quite difficult to understand what you mean without seeing any code, but it sounds like you can use an Observable for this use case: QueryComponent makes an Observable available and ClockComponent subscribes to it.

You may wish to look at [this article](http://blog.angular-university.io/how-to-build-angular2-apps-using-rxjs-observable-data-services-pitfalls-to-avoid/) which shows some examples of how to communicate between different components in an Angular project.

As this is a GitHub project and not a support forum, I'm afraid I can't help much more. I'm closing this issue as it's not about `ng2-mqtt-demo` itself but a general question about Angular 2.

**Comment by VirendraWankhede** [comment]
Its my mistake, i used ng2-simple-mq and i was confused to pass message. And after work with ngx-mqtt now my application is working fine. Thanku so much ! and sorry for my comments which was related to query.
