### ISSUE TITLE
EXCEPTION: Uncaught (in promise): TypeError: this.once is not a function

### ISSUE THREAD

**Issue by alvesman** [sjmf/ng2-mqtt-demo#8]
Hi,
First, thanks for sharing this! Had no problems cloning and running your code.
**The problem:**
I would like to incorporate this code on a SPA, in visual studio 2017, I made following this instructions: https://jonhilton.net/2017/02/21/create-a-vs2017-angular-2-and-net-core-site-using-the-command-line/ and https://channel9.msdn.com/Events/Visual-Studio/Visual-Studio-2017-Launch/WEB-103

 I’m stuck now on this error “**EXCEPTION: Uncaught (in promise): TypeError: this.once is not a function**” that happens in “mqtt.service.ts” when creating the connection:

    // Create the client and listen for its connection
    this.client = mqtt.connect(url, options);

I’m stuck here.

The attached file is the solution I’m using minus .vs, .git and node_modules folders.
Probably it's just a newbie problem but I’m really stuck here for quite some time (shame to say)

[monitor.zip](https://github.com/sjmf/ng2-mqtt-demo/files/905627/monitor.zip)

best regards,
Manuel Alves

**Comment by alvesman** [comment]
Sorry for bothering you. Newbie mistake...
My package.json was missing:
```
    "core-js": "^2.4.1",
    "mqtt": "^1.14.1"
```

Once again, thank you for sharing this code.
Best regards
Manuel Alves

**Comment by sjmf** [comment]
Thanks for posting your solution, glad you found the issue.
